# Generated by Django 2.1.7 on 2019-02-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='책 제목')),
                ('author', models.CharField(max_length=25, verbose_name='글쓴이')),
                ('publisher', models.CharField(max_length=25, verbose_name='출판사')),
                ('date', models.CharField(max_length=15, verbose_name='출판일')),
                ('updated', models.CharField(max_length=15, verbose_name='수정일')),
            ],
        ),
    ]
