# Generated by Django 2.1.7 on 2019-02-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlist',
            name='url',
            field=models.CharField(default='', max_length=200, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
